server:
  port: 8889

logging:
  file:
    path: logs

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: 0316
#type-aliases-package  可以理解成实体类包名，设置这个属性以后，在mapper文件中sql--parameterType就不用写全路径了
#mapper-locations  mapper文件路径
mybatis:
  type-aliases-package: com.test.model
  mapper-locations:
    - mapper/*