server:
  port: 8888

#logging:
#  config: classpath:logback.xml

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: 0316

mybatis:
    type-aliases-packages: com.test.bean
    mapper-locations:
      - mapper/*